### ISSUE TITLE
Strange rendering result on non-retina display on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [skatiyar/pacman#1]
Hi, thank you for using Ebiten!

I found your pacman on browser on non-retina display doesn't run well (I'll add a screenshot later when I'm available). You specify `1 / ebiten.DeviceScaleFactor()` for the game scale, which means that the whole screen size in device-independent pixels (= px on browsers) would change by the resolution (`window.devicePixelRatio` on browsers). The game screen size is 712x1220, and `iframe`'s size is specified `356px` and `610px`, so I guess the game properly works only when `ebiten.DeviceScaleFactor()` is 2. 

Thus, always specifying `0.5` should work in there in this case.

**Comment by hajimehoshi** [comment]
Huh? I was wondering if that change related to this issue...

**Comment by hajimehoshi** [comment]
I've confirmed this fixed the problem anyway... Probably there was something I missed. Thank you for fixing this, and thank you for using Ebiten again!

**Comment by skatiyar** [comment]
Sorry I forgot to refer issue in previous commit message, so had to do it in next commit.
Thanks for building Ebiten, a really cool game engine.
