### ISSUE TITLE
Input controls

### ISSUE THREAD

**Issue by jonmaim** [skatiyar/pacman#2]
On the demo, I'm not sure I see pacman and when I use the arrow keys nothing seems to happen. Pretty cool otherwise!

How do you make a web game in GoLang btw? 😄

**Comment by skatiyar** [comment]
Can you please take a snapshot and add to issue, will help me debug.

I use [Gopherjs](https://github.com/gopherjs/gopherjs) to compile Go code to JS. The lib [Ebiten](https://github.com/hajimehoshi/ebiten) supports graphics through WebGl.

**Comment by cjbassi** [comment]
That's pretty neat, you should document how it works in the readme.

**Comment by skatiyar** [comment]
Closing issue since it seems related to wrong rendering in iframe because of DevicePixel ratio. Issue is fixed by an earlier commit.
