### ISSUE TITLE
Is this my problem?

### ISSUE THREAD

**Issue by RainNameless** [skatiyar/pacman#5]
$ go build -o pacman main.go
go: downloading github.com/hajimehoshi/ebiten v1.8.0
verifying github.com/hajimehoshi/ebiten@v1.8.0: checksum mismatch
        downloaded: h1:8PLZSQ//ukmVJl3LuPBdiWmV/xh0tGcBAW+PDO7dyuA=
        go.sum:     h1:m4XT/9S+6L0ib9EiWLDCSNcgm4sQy2/iTgGy/ypYHvE=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

**Comment by hajimehoshi** [comment]
Old Go compiler might generate a different go.sum, so the solution would be to regenerate go.sum by @skatiyar

**Comment by RainNameless** [comment]
> Old Go compiler might generate a different go.sum, so the solution would be to regenerate go.sum by @skatiyar

I am using a new compiler, can I change the old version of the go compiler to execute?

**Comment by hajimehoshi** [comment]
I'm not sure why you translated my comment into Chinese...

> I am using a new compiler, can I change the old version of the go compiler to execute?

Possible:

```
go get golang.org/dl/go1.12.9
go1.12.9 download
```

But another problem is that Ebiten assumes Go 1.12 or later, so I don't know pacman works with Go 1.12.

**Comment by RainNameless** [comment]
> I'm not sure why you translated my comment into Chinese...
> 
> > I am using a new compiler, can I change the old version of the go compiler to execute?
> 
> Possible:
> 
> ```
> go get golang.org/dl/go1.12.9
> go1.12.9 download
> ```
> 
> But another problem is that Ebiten assumes Go 1.12 or later, so I don't know pacman works with Go 1.12.



> 我不确定您为什么将我的评论翻译成中文...
> 
> > 我使用的是新的编译器，可以更改旧版本的go编译器执行吗？
> 
> 可能：
> 
> ```
> go get golang.org/dl/go1.12.9
> go1.12.9 download
> ```
> 
> 但是另一个问题是Ebiten假定使用Go 1.12或更高版本，所以我不知道pacman可用于Go 1.12。



> I'm not sure why you translated my comment into Chinese...
> 
> > I am using a new compiler, can I change the old version of the go compiler to execute?
> 
> Possible:
> 
> ```
> go get golang.org/dl/go1.12.9
> go1.12.9 download
> ```
> 
> But another problem is that Ebiten assumes Go 1.12 or later, so I don't know pacman works with Go 1.12.



> I'm not sure why you translated my comment into Chinese...
> 
> > I am using a new compiler, can I change the old version of the go compiler to execute?
> 
> Possible:
> 
> ```
> go get golang.org/dl/go1.12.9
> go1.12.9 download
> ```
> 
> But another problem is that Ebiten assumes Go 1.12 or later, so I don't know pacman works with Go 1.12.

I am Chinese because of the Google Translate plugin，LOL , Thanks, brother.

**Comment by RainNameless** [comment]
> I'm not sure why you translated my comment into Chinese...
> 
> > I am using a new compiler, can I change the old version of the go compiler to execute?
> 
> Possible:
> 
> ```
> go get golang.org/dl/go1.12.9
> go1.12.9 download
> ```
> 
> But another problem is that Ebiten assumes Go 1.12 or later, so I don't know pacman works with Go 1.12.

Because of the Google Translate plugin, I am Chinese,LOL,Thanks, brother。

**Comment by skatiyar** [comment]
@RainNameless can you try now, I've updated the dependencies to fix checksum issue. Thanks reporting the issue.
